### ISSUE TITLE
launcher-static.yml not being updated

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/gradle-java-distribution#144]
While trying to run our ETE tests, if our commit hash changes, the launcher-static.yml isn't updated. This causes our ETE tests to fail because the tgz has the new jars but the launcher-static.yml is referencing the old ones.

@hsaraogi @jeremyk-91

**Comment by uschi2000** [comment]
Can you confirm this behaviour on the latest release (1.1.0), please?

**Comment by SerialVelocity** [comment]
Whoops, I read our version as 1.1.0 but we're only on 1.0.1. I'll upgrade and see if it fixes the problem.

**Comment by SerialVelocity** [comment]
Actually, looks like the only update was adding environment variables. Chances are this is an issue still. (I'll confirm when it happens again)

**Comment by uschi2000** [comment]
Ben, can you provide a repro for this? Not sure where to look otherwise.

**Comment by SerialVelocity** [comment]
Will do once we figure out how to repro it :)

**Comment by iamdanfox** [comment]
**I think it may be worth blacklisting 1.1.0 and 1.0.1 too because there is a reliable repro to make gradle java distribution produce non-functional tars.**

We upgraded to gradle-java-distribution 1.1.0 yesterday and this bug broke our release.

## Repro:

1. Using gradle 3.2, with a daemon running happily
1. Checkout `my-project` at tag 0.3.0 (which uses gradle-java-distribution 1.1.0 or 1.0.1)
1. run `git clean -xdf`
1. run `./gradlew distTar`. Observe that the launcher-static.yml and launcher-check.yml contain the correct 0.3.0
1. run `git tag 0.3.1`
1. run `./gradlew distTar`

Note: I suspect there are a variety of different options for step (5) that will break the next distTar, possibly including the environment variables stuff Ben mentions above!

## Expected:
The resultant dist should contain a `launcher-static.yml` and `launcher-check.yml` that both reference `my-project-0.3.1.jar` in their classpath argument.  `./service/bin/init.sh` should start up the service correctly.

## Actual:
The `launcher-static.yml` and `launcher-check.yml` files reference the missing jar `my-project-0.3.0.jar` in their classpath argument.  The plugin then produces a broken tar, `./service/bin/init.sh start` will fail with the message:

```
Error: Could not find or load main class com.palantir.myproject.MyProjectApplication
```

## Workaround

`./gradlew distTar --rerun-tasks` will produce a functioning tar again.

## Explanation

I strongly suspect that this is caused by https://github.com/palantir/gradle-java-distribution/pull/138, which enables incremental behaviour for tasks.  Specifically, the `LaunchConfigTask` [does not declare the classpath as an @Input][1].  Any change to the classpath (e.g. a new tag) is then not reflected in the new launcher-{static, check} files, leading to non-functional releases.

gradle-java-distribution version 1.0.0 does not exhibit this behaviour.

[1]:https://github.com/palantir/gradle-java-distribution/blob/23cdf3753fc73471389d6c6ea8ba34840061726f/src/main/groovy/com/palantir/gradle/javadist/tasks/LaunchConfigTask.groovy#L103

 cc @a-k-g

**Comment by ash211** [comment]
Thanks for this great investigation @iamdanfox !

**Comment by uschi2000** [comment]
@iamdanfox can you please try 1.2.0-rc4 an report back if this fixes your problem? https://github.com/palantir/gradle-java-distribution/releases/tag/1.2.0-rc4 ?

**Comment by uschi2000** [comment]
Confirmed with @iamdanfox that this issue is fixed.
