### ISSUE TITLE
Allow consumers to resolve conflicts between recommended dependencies for manifests

### ISSUE THREAD

**Issue by gregakinman** [palantir/gradle-java-distribution#279]
Situation:

- Project A directly depends on library B.
- Library B directly depends on version 1 of library C and declares this as a recommended product dependency in its JAR manifest.
- Library B directly depends on library D, which has declared version 2 of library C as a recommended product dependency in its JAR manifest.
- As a result, there are now two versions of library C recommended to project A.

sls-packaging should provide a way to allow the consumer to reconcile these if they are different - currently it just lets them slide if they're the same (https://github.com/palantir/sls-packaging/pull/244).

**Comment by dansanduleac** [comment]
You can short circuit the conflict detection logic now by
1) replacing the distribution extension's `productDependenciesConfig` with an empty/bogus one:
    ```
    distribution {
        productDependenciesConfig = configurations.detachedConfiguration()
    }
    ```
2) Declaring the min/max/recommended versions of your own product dependencies manually, [like so](https://github.palantir.build/foundry/foundry/blob/126da1f3202d09940ed0bd613900ea670d97ee36/foundry-fsclient/build.gradle#L90-L96), but unlike in the example, nest these `productDependency` blocks under your `distribution` block.

However, #293 should address the issues where the dependency ranges differ but are otherwise non-disjoint.

**Comment by gregakinman** [comment]
Nice, thanks for the PR @dansanduleac. I'd consider this fixed.
