### ISSUE TITLE
Init.sh status no longer returns a value to stdout

### ISSUE THREAD

**Issue by jboreiko** [palantir/gradle-java-distribution#336]
This changed after the move to use the go-init logic.  We maintain sls-spec compatibility by returning the appropriate exit codes but fail to return any values to stdout.  Though undocumented this can be relied upon by scripts and is a breaking change as a result.

We should consider the following:
1) offering a fix to return to the old behavior and blacklisting all products containing the behavioral change
2) major bumping the library and requesting consumers to major version bump as well

Though internally this behavior is not relied upon by our main consumer, external users as well an externally deployed internal applications can suffer breaks.

**Comment by ChristopherRogers1991** [comment]
Just to note it, according to the spec:

> An init script at the path service/bin/init.sh which supports the start,stop, and status commands. These commands should behave in accordance with the [Linux Standard Base](http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html) specification.

LSB says the `status` command will "print the current status of the service."

If we go the major version bump route, and stop producing output, we should note the change in the doc as well.

**Comment by cbrockington** [comment]
https://github.com/palantir/go-java-launcher/pull/63 somewhat reverts the behavioural change.

Given the looseness of the specification though, this still doesn't mean that the print messages should not be relied on.  That PR adds print messages back into status reporting though their structure has changed, which it's reasonable to pose as a minor change since they are not specified anywhere as part of the API.

**Comment by jboreiko** [comment]
Closing out as resolved.
