### ISSUE TITLE
./gradlew createManifest (or ./gradlew --write-locks) shouldn't require compilation

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-java-distribution#421]
## What happened?

From 3.0 onwards, we ask people to run `./gradlew --write-locks` to keep their lockfiles up to date.  Currently it can be very slow because it can involve compiling the project.

## What did you want to happen?

The task should be as snappy as possible. Sure, we have to resolve dependencies in order to find out what their manifest contains, but I think it should be possible to avoid actually compiling the java files in a repo just to get the manifest!

**Comment by dansanduleac** [comment]
Not sure if we can do this actually, without some more sweeping changes to sls-packaging and conjure that change and centralize how we configure the manfiest.

Right now, we configure the jar manifest as part of a task that jar depends on..
it's technially impossible to know where this would happen, which is why we have to actually run the jar task (along with all its dependencies) in order to get the manifest.

The only way we could do this better is if the manifest were somehow configured as a Property, and we could set that as an input on the createManifest task.

**Comment by iamdanfox** [comment]
Fixed by https://github.com/palantir/sls-packaging/pull/451
