### ISSUE TITLE
createManifest "succeeds" when ran with mismatched version of Java

### ISSUE THREAD

**Issue by VVKot** [palantir/gradle-java-distribution#940]
## What happened?

I was on this commit https://github.p.b/foundry/p2-export/pull/1031/commits/ab69e76dc12aac21bd1969044284ca7bcd5b112b on my branch when build failed with `p2-export/product-dependencies.lock is out of date` . I tried to rewrite locks but that didn't result in any changes:

1. https://gradle.p.b/s/gdzunvdch3im2
1. https://gradle.p.b/s/tfxzms4dddamq

Turns out that I was running the `gw` with Java 11 while this service is using 14. After switching to 14, the same `./gradlew :p2-export:createManifest` command successfully regenerated lock file.

## What did you want to happen?

Ideally command should have failed and point me to switching over to Java 14.

**Comment by dansanduleac** [comment]
It seems to me that we currently rely entirely on the runtime (i.e. circle config) to determine what version of JDK we should require, and so local runs are bound to diverge in behaviour.

Perhaps instead we should enforce setting a targetCompatibility (though most likely sourceCompatibility as well) of the jdk we want, then this [preflight logic ](https://github.p.b/foundry/gradle-preflight/pull/668/files#diff-16b1f433908f964209d588ab2dedb74fR36-R48) could use that to infer what JVM _must_ be available on the stacks.

**Comment by dansanduleac** [comment]
Looking into this some more, it turns out that we're not deriving the JDK from the current runtime's version (directly), but via the `targetCompatibility`. Which indeed, if you don't set a source/target compatibility, will default to the version of the JVM you ran gradle with.
So, the solution in this case is to make sure you have a `sourceCompatibility = 14` in your product's build.gradle.
